{"name": "Тест оформления заказа залогиненным пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Флюоресцентная булка R2-D3']\"}\n  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001048c2a80 chromedriver + 4385408\n1   chromedriver                        0x00000001048bb38c chromedriver + 4354956\n2   chromedriver                        0x00000001044d8b0c chromedriver + 281356\n3   chromedriver                        0x000000010451b2f8 chromedriver + 553720\n4   chromedriver                        0x0000000104553d24 chromedriver + 785700\n5   chromedriver                        0x000000010450feec chromedriver + 507628\n6   chromedriver                        0x00000001045108c4 chromedriver + 510148\n7   chromedriver                        0x000000010488a43c chromedriver + 4154428\n8   chromedriver                        0x000000010488eea0 chromedriver + 4173472\n9   chromedriver                        0x000000010486fff8 chromedriver + 4046840\n10  chromedriver                        0x000000010488f78c chromedriver + 4175756\n11  chromedriver                        0x0000000104862fb8 chromedriver + 3993528\n12  chromedriver                        0x00000001048ad21c chromedriver + 4297244\n13  chromedriver                        0x00000001048ad398 chromedriver + 4297624\n14  chromedriver                        0x00000001048baf84 chromedriver + 4353924\n15  libsystem_pthread.dylib             0x00000001902e2f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001902ddd34 thread_start + 8", "trace": "self = <tests.test_main_function.TestMainFunction object at 0x107441250>, auth_user = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8b6048ea6e91330ba6e824388a6ccf18\")>\n\n    @allure.title(\"Тест оформления заказа залогиненным пользователя\")\n    @allure.description(\"Залогиненный пользователь может оформить заказ\")\n    def test_make_order_by_auth_account(self, auth_user):\n        driver = auth_user\n        main_page = MainPage(driver)\n>       main_page.add_ingredient()\n\ntests/test_main_function.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/main_page.py:33: in add_ingredient\n    self.drag_and_drop_element(MainPageLocators.BUN_INGREDIENT, MainPageLocators.BASKET)\npages/base_page.py:77: in drag_and_drop_element\n    drag = self.driver.find_element(*locator_1)\n.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:748: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x1101b4400>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...0001902e2f94 _pthread_start + 136\\\\n16  libsystem_pthread.dylib             0x00000001902ddd34 thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Флюоресцентная булка R2-D3']\"}\nE         (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x00000001048c2a80 chromedriver + 4385408\nE       1   chromedriver                        0x00000001048bb38c chromedriver + 4354956\nE       2   chromedriver                        0x00000001044d8b0c chromedriver + 281356\nE       3   chromedriver                        0x000000010451b2f8 chromedriver + 553720\nE       4   chromedriver                        0x0000000104553d24 chromedriver + 785700\nE       5   chromedriver                        0x000000010450feec chromedriver + 507628\nE       6   chromedriver                        0x00000001045108c4 chromedriver + 510148\nE       7   chromedriver                        0x000000010488a43c chromedriver + 4154428\nE       8   chromedriver                        0x000000010488eea0 chromedriver + 4173472\nE       9   chromedriver                        0x000000010486fff8 chromedriver + 4046840\nE       10  chromedriver                        0x000000010488f78c chromedriver + 4175756\nE       11  chromedriver                        0x0000000104862fb8 chromedriver + 3993528\nE       12  chromedriver                        0x00000001048ad21c chromedriver + 4297244\nE       13  chromedriver                        0x00000001048ad398 chromedriver + 4297624\nE       14  chromedriver                        0x00000001048baf84 chromedriver + 4353924\nE       15  libsystem_pthread.dylib             0x00000001902e2f94 _pthread_start + 136\nE       16  libsystem_pthread.dylib             0x00000001902ddd34 thread_start + 8\n\n.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "description": "Залогиненный пользователь может оформить заказ", "steps": [{"name": "Добавление ингредиента в заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Флюоресцентная булка R2-D3']\"}\n  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001048c2a80 chromedriver + 4385408\n1   chromedriver                        0x00000001048bb38c chromedriver + 4354956\n2   chromedriver                        0x00000001044d8b0c chromedriver + 281356\n3   chromedriver                        0x000000010451b2f8 chromedriver + 553720\n4   chromedriver                        0x0000000104553d24 chromedriver + 785700\n5   chromedriver                        0x000000010450feec chromedriver + 507628\n6   chromedriver                        0x00000001045108c4 chromedriver + 510148\n7   chromedriver                        0x000000010488a43c chromedriver + 4154428\n8   chromedriver                        0x000000010488eea0 chromedriver + 4173472\n9   chromedriver                        0x000000010486fff8 chromedriver + 4046840\n10  chromedriver                        0x000000010488f78c chromedriver + 4175756\n11  chromedriver                        0x0000000104862fb8 chromedriver + 3993528\n12  chromedriver                        0x00000001048ad21c chromedriver + 4297244\n13  chromedriver                        0x00000001048ad398 chromedriver + 4297624\n14  chromedriver                        0x00000001048baf84 chromedriver + 4353924\n15  libsystem_pthread.dylib             0x00000001902e2f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001902ddd34 thread_start + 8\n\n", "trace": "  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/pages/main_page.py\", line 33, in add_ingredient\n    self.drag_and_drop_element(MainPageLocators.BUN_INGREDIENT, MainPageLocators.BASKET)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/pages/base_page.py\", line 77, in drag_and_drop_element\n    drag = self.driver.find_element(*locator_1)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Перетаскивание элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Флюоресцентная булка R2-D3']\"}\n  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x00000001048c2a80 chromedriver + 4385408\n1   chromedriver                        0x00000001048bb38c chromedriver + 4354956\n2   chromedriver                        0x00000001044d8b0c chromedriver + 281356\n3   chromedriver                        0x000000010451b2f8 chromedriver + 553720\n4   chromedriver                        0x0000000104553d24 chromedriver + 785700\n5   chromedriver                        0x000000010450feec chromedriver + 507628\n6   chromedriver                        0x00000001045108c4 chromedriver + 510148\n7   chromedriver                        0x000000010488a43c chromedriver + 4154428\n8   chromedriver                        0x000000010488eea0 chromedriver + 4173472\n9   chromedriver                        0x000000010486fff8 chromedriver + 4046840\n10  chromedriver                        0x000000010488f78c chromedriver + 4175756\n11  chromedriver                        0x0000000104862fb8 chromedriver + 3993528\n12  chromedriver                        0x00000001048ad21c chromedriver + 4297244\n13  chromedriver                        0x00000001048ad398 chromedriver + 4297624\n14  chromedriver                        0x00000001048baf84 chromedriver + 4353924\n15  libsystem_pthread.dylib             0x00000001902e2f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001902ddd34 thread_start + 8\n\n", "trace": "  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/pages/base_page.py\", line 77, in drag_and_drop_element\n    drag = self.driver.find_element(*locator_1)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/p.sinegubov/Downloads/Личные данные/git/Диплом_Павел_Синегубов_8/Diplom_3/.venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator_1", "value": "('xpath', \"//p[text()='Флюоресцентная булка R2-D3']\")"}, {"name": "locator_2", "value": "('class name', 'BurgerConstructor_basket__list__l9dp_')"}], "start": 1719543852253, "stop": 1719543852262}], "start": 1719543852253, "stop": 1719543852262}], "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1719543852253, "stop": 1719543852263, "uuid": "75b30483-93af-4eaf-aa48-58896f105bf7", "historyId": "5dc558d2e084e925f5f404050c8bf78b", "testCaseId": "9cf0da10b45c87ffc77066bda28a83e2", "fullName": "tests.test_main_function.TestMainFunction#test_make_order_by_auth_account", "labels": [{"name": "feature", "value": "Проверка основного функционала"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_main_function"}, {"name": "subSuite", "value": "TestMainFunction"}, {"name": "host", "value": "NB0727.local"}, {"name": "thread", "value": "67328-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_main_function"}]}